workflows:
  # Development Workflow
  dev-workflow:
    name: Development Workflow
    environment:
      flutter: 3.19.0
      vars:
        SECRET_TOKEN: $SECRET_TOKEN
        OPEN_KEY: $OPEN_KEY
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Build Debug Package for QA Testing
        script: flutter build apk --debug
      - name: Read environment Vars
        script: |
          echo "Testing print variables"
          echo $OPEN_KEY
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - claudio.junior@bairesdev.com
        notify_on_build_start: true
        notify_on_build_success: true
        notify_on_build_failure: true

  # Production Workflow
  prod-workflow:
    name: Production Workflow
    environment:
      vars:
        SECRET_TOKEN: $SECRET_TOKEN
        OPEN_KEY: $OPEN_KEY
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Build and release for production
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab


  basic-flutter-workflow:
    name: Basic Flutter Workflow (develop)

    environment:
      vars:
        # Read Codemagic' environment variables
        KEY_PASSWORD: $KEY_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        SECRET_TOKEN: $SECRET_TOKEN
        OPEN_KEY: $OPEN_KEY
        GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: Encrypted(HKJGfjhg234jhg234==)

    scripts:
      - name: Show Private Environment Variables
        script: |
          echo "Codemagic Mac Mini envVars"
          echo "API Key: $KEY_PASSWORD"
          echo "Key Store PW: $KEYSTORE_PASSWORD"
          echo "Key Alias: $KEY_ALIAS"
          echo "$printenv"
      - name: Show Non-Private Environment Variables
        script: |
          echo "Open Key: $OPEN_KEY"
          echo $OPEN_KEY
          echo $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
          echo $printenv